Fix error when running tcex commands
Fix error (AttributeError: 'tuple' object has no attribute 'expandtabs') caused by typo. There is an extra dangling comma (,) which resulted in a tuple being created instead of a string and caused error in subsequent function expecting a string.